// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  modal: {
    cancelLabel: 'Cancel';
    confirmLabel: 'Confirm';
  };
  root: {
    'theme-mode': 'Dark Mode';
    'language-switch': 'Language';
  };
  error: {
    title: 'An unexpected error occurred while loading the page.';
    content: 'Please try again shortly, or go back to the previous page.';
    backButton: 'Go Back';
    refreshButton: 'Refresh';
  };
  'not-found': {
    title: '404 PAGE NOT FOUND';
    content: "This page doesn't exist.";
    button: 'Go to Home';
  };
  main: {
    request: 'Issue Request';
    check: 'Issue Check';
  };
  request: {
    itemName: 'Title';
    description: 'Description';
    requestorName: 'Requestor name';
    requestorEmail: 'Requestor Email';
    requestorPhone: 'Requestor Phone(Optional)';
    kakaoDescription1: 'You can check the progress of your issue through the KakaoTalk Plus Friend';
    kakaoDescription2: 'channel.';
    ErrorMessage: 'Please enter at least {minLength} characters.';
    emailErrorMessage: 'Please verify the format of your email address';
    itemNamePlaceholder: 'Issue title';
    descriptionPlaceholder: 'Issue description';
    requestorNamePlaceholder: 'Cle';
    requestorEmailPlaceholder: 'cle@cle.vision';
    requestorPhonePlaceholder: '02-460-4228';
    submit: 'Submit';
    successPopupContent: 'Issue submitted successfully.';
    failPopupContent: 'Failed to submit issue.';
    successPopupTitle: 'Success';
    failPopupTitle: 'Fail';
  };
};
export default messages;
