// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  modal: {
    cancelLabel: 'Cancel';
    confirmLabel: 'Confirm';
  };
  root: {
    'theme-mode': 'Dark Mode';
    'language-switch': 'Language';
  };
  error: {
    title: 'An unexpected error occurred while loading the page.';
    content: 'Please try again shortly, or go back to the previous page.';
    backButton: 'Go Back';
    refreshButton: 'Refresh';
  };
  'not-found': {
    title: '404 PAGE NOT FOUND';
    content: "This page doesn't exist.";
    button: 'Go to Home';
  };
};
export default messages;
